"""
Base scraper interface and FlightRecord canonical data model.

All airline scrapers implement BaseScraper and return FlightRecord objects.
The FlightRecord is the contract between the scraping layer and the DB layer —
nothing downstream touches raw API responses.
"""

from __future__ import annotations

import logging
import random
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date, datetime

import httpx
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
    wait_random,
)

from config.settings import (
    SCHEDULER_REFRESH_INTERVAL_MIN,
    SCRAPE_DAYS_AHEAD,
    SCRAPE_DENSE_DAYS,
    SCRAPE_SPARSE_STEP,
    SCRAPER_BLOCK_THRESHOLD,
    SCRAPER_COOLDOWN_MAX_S,
    SCRAPER_MAX_RETRIES,
    SCRAPER_MIN_DELAY_S,
)

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class FlightRecord:
    """
    Canonical representation of a single bookable award flight option.

    One FlightRecord = one cabin class on one departure date for one itinerary.
    Frozen (immutable) to prevent accidental mutation in the pipeline.
    """

    # --- Route ---
    origin: str  # 3-letter IATA, uppercase, e.g. "EWR"
    destination: str  # 3-letter IATA, uppercase, e.g. "LAX"
    date: date  # Local departure date

    # --- Loyalty program ---
    airline: str  # Operating carrier IATA code: "UA", "AA", etc.
    program: str  # Loyalty program name: "MileagePlus"

    # --- Provenance ---
    source: str  # Scraper that produced this row, e.g. "alaska"
    # Lets us filter/audit which scraper each row came from, independent of
    # `airline` (two scrapers can surface the same operating carrier).

    # --- Award cost ---
    points_cost: int  # Miles/points required. Always > 0.
    cash_cost: float  # Taxes + fees in USD. Can be 0.0.

    # --- Itinerary ---
    cabin_class: str  # "economy" | "premium_economy" | "business" | "first"
    stops: int  # 0 = nonstop, 1 = one stop, etc.
    available_seats: int  # Seats bookable at this price point. -1 = unknown.

    # --- Freshness (UTC; the _utc suffix makes the timezone explicit) ---
    scraped_at_utc: datetime  # UTC timestamp of when this was fetched
    expires_at_utc: datetime  # UTC timestamp after which this is considered stale

    # --- Optional metadata ---
    raw_flight_number: str | None = None
    # Single flight: "UA 123"
    # Connection:    "UA 123+UA 456"
    # Multi-leg unknown: use "UNKNOWN" (never None — UNIQUE constraint depends on it)

    partner_airline: str | None = None
    # Set when booking partner space, e.g. "NH" for ANA on MileagePlus

    # --- Timing (LOCAL airport time — what the traveler reads off the board, not an instant) ---
    departure_time_local: datetime | None = None  # local departure-airport time
    arrival_time_local: datetime | None = None  # local arrival-airport time
    duration_minutes: int | None = None  # Total journey time (includes layovers)

    # --- Aircraft ---
    aircraft_type: str | None = None  # IATA aircraft code, e.g. "738", "321"

    # --- Fare details ---
    is_saver: bool = False  # True for restricted/saver fares
    fare_class: str | None = None  # Booking class/bucket, e.g. "XN", "I"

    # --- Connection details ---
    layover_airports: str | None = None  # Comma-separated IATA codes, e.g. "ORD,DFW"
    layover_duration_minutes: int | None = None  # Total time at layover airports
    next_day_arrival: bool = False  # True if arrival date > departure date
    mixed_cabin: bool = False  # True if different cabins across legs

    def __post_init__(self) -> None:
        """Validate invariants. Runs even on frozen dataclasses."""
        if len(self.origin) != 3:
            raise ValueError(f"Invalid origin IATA: {self.origin!r}")
        if len(self.destination) != 3:
            raise ValueError(f"Invalid destination IATA: {self.destination!r}")
        if not self.source:
            raise ValueError("source (scraper name) must be set")
        if self.points_cost <= 0:
            raise ValueError(f"points_cost must be > 0, got {self.points_cost}")
        if self.cabin_class not in ("economy", "premium_economy", "business", "first"):
            raise ValueError(f"Unknown cabin_class: {self.cabin_class!r}")
        if self.expires_at_utc <= self.scraped_at_utc:
            raise ValueError("expires_at_utc must be after scraped_at_utc")


@dataclass(frozen=True)
class CashFareRecord:
    """Cheapest cash fare for one flight × cabin × date — the CPP cash anchor.

    Mirrors the cash_fares table. flight_number is the first-segment number, generated by the
    same code path as the award FlightRecord so cash joins award 1:1.
    """

    origin: str
    destination: str
    date: date
    airline: str  # marketing IATA, e.g. "AS" — matches flights.airline for the join
    cabin_class: str  # economy | premium_economy | business | first
    flight_number: str  # "AS 123" (never empty); NOT NULL in the table
    cash_price: float  # cheapest cash fare in `currency`, > 0
    scraped_at_utc: datetime
    expires_at_utc: datetime
    currency: str = "USD"
    source: str = "alaska_cash"

    def __post_init__(self) -> None:
        if len(self.origin) != 3 or len(self.destination) != 3:
            raise ValueError(f"Invalid IATA: {self.origin!r}/{self.destination!r}")
        if not self.flight_number:
            raise ValueError("flight_number must be set")
        if self.cash_price <= 0:
            raise ValueError(f"cash_price must be > 0, got {self.cash_price}")
        if self.cabin_class not in ("economy", "premium_economy", "business", "first"):
            raise ValueError(f"Unknown cabin_class: {self.cabin_class!r}")
        if not self.source:
            raise ValueError("source must be set")
        if self.expires_at_utc <= self.scraped_at_utc:
            raise ValueError("expires_at_utc must be after scraped_at_utc")


class BaseScraper(ABC):
    """
    Abstract base class for all airline award scrapers.

    Subclasses implement fetch_raw() and normalize().
    The scrape() template method chains them together.

    Adding a new airline:
        1. Create scrapers/<airline_code_lower>.py
        2. Subclass BaseScraper
        3. Set airline_code, program_name, and source class attributes
        4. Implement fetch_raw() and normalize() (stamp source=self.source on records)
        5. Add routes to config/routes.py
    """

    airline_code: str  # e.g. "UA" — set as class attribute in subclass
    program_name: str  # e.g. "MileagePlus"
    source: str  # scraper slug stamped onto every FlightRecord, e.g. "alaska"

    # --- scheduling / pacing (read by the scheduler via getattr; override per airline) ---
    # Shared across transports (HttpScraper + BrowserScraper). Defaults come from settings.
    min_delay_s: float = SCRAPER_MIN_DELAY_S
    block_threshold: int = SCRAPER_BLOCK_THRESHOLD
    refresh_interval_min: int = SCHEDULER_REFRESH_INTERVAL_MIN
    scrape_days_ahead: int = SCRAPE_DAYS_AHEAD
    dense_days: int = SCRAPE_DENSE_DAYS
    sparse_step: int = SCRAPE_SPARSE_STEP
    # Max routes scraped per refresh run (bounds run time under refresh_interval_min).
    max_routes_per_run: int = 12

    @abstractmethod
    def fetch_raw(self, origin: str, dest: str, travel_date: date) -> dict:
        """
        Make the HTTP request and return the parsed JSON response.

        Retry logic lives here (tenacity decorators on the implementation).
        Raise on unrecoverable errors; return empty dict if no results.
        """
        ...

    @abstractmethod
    def normalize(self, raw: dict, origin: str, dest: str, travel_date: date) -> list[FlightRecord]:
        """
        Map raw API response to a list of FlightRecord objects.

        Returns [] if no award space is available (not an error).
        Skips individual records that fail validation (logs warning).
        """
        ...

    def scrape(self, origin: str, dest: str, travel_date: date) -> list[FlightRecord]:
        """
        Template method: fetch_raw → normalize.
        Subclasses should not override this.
        """
        logger.debug("[%s] Scraping %s→%s on %s", self.source, origin, dest, travel_date)
        raw = self.fetch_raw(origin, dest, travel_date)
        records = self.normalize(raw, origin, dest, travel_date)
        logger.debug(
            "[%s] %s→%s on %s: %d records", self.source, origin, dest, travel_date, len(records)
        )
        return records


# ---------------------------------------------------------------------------
# Shared HTTP machinery for API-based scrapers
# ---------------------------------------------------------------------------


class ScraperBlockedError(Exception):
    """Raised after repeated 403/406s — the airline's WAF is rate-limiting/blocking the IP.

    Signals the caller to stop the run and back off rather than hammering a banned IP
    (which only deepens the ban). One per scraper instance; the scheduler catches it to
    abort that airline's run and apply a longer cool-down.
    """


# A plausible desktop-Chrome header block. Subclasses override `base_headers` with the
# exact headers from their cURL (airline endpoints are picky about sec-* / Referer).
_DEFAULT_HEADERS: dict[str, str] = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/136.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",  # br needs the `brotli` package to decode
    "sec-ch-ua": '"Chromium";v="136", "Google Chrome";v="136", "Not-A.Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "priority": "u=1, i",
}

# Headers used for the optional homepage prime (a real browser navigates first).
_PRIME_HEADERS: dict[str, str] = {
    "Accept": (
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
    ),
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
}


def _is_retryable(exc: BaseException) -> bool:
    """Retry transient transport errors and 429/5xx — but NOT 403/406 (handled inline)."""
    if isinstance(exc, httpx.TimeoutException):
        return True
    if isinstance(exc, httpx.RemoteProtocolError):
        return True
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in (429, 500, 502, 503, 504)
    return False


class HttpScraper(BaseScraper):
    """BaseScraper + the shared anti-rate-limit HTTP machinery (hoisted from Alaska).

    A paced, retrying, circuit-broken httpx client. Subclasses set the class-attr config
    below and implement ``fetch_raw`` (build the request → ``self._request(...)`` → parse the
    body into a dict) and ``normalize``. Everything resilience-related — optional WAF priming,
    per-request pacing, tenacity retry on 429/5xx, escalating 403/406 back-off, and the
    consecutive-block circuit breaker — lives here.

    Per-airline conservatism is configured purely via class attrs (no env churn): override
    ``min_delay_s`` / ``block_threshold`` / ``refresh_interval_min`` / scrape-window attrs.
    """

    # --- request config (override per airline) ---
    base_headers: dict[str, str] = _DEFAULT_HEADERS
    prime_url: str | None = None  # None → skip priming (most JSON APIs don't need it)
    prime_headers: dict[str, str] | None = None
    http2: bool = True

    # --- httpx-only pacing knob (cooldown ceiling for the 403/406 circuit breaker) ---
    cooldown_max_s: float = SCRAPER_COOLDOWN_MAX_S

    def __init__(self) -> None:
        self._client = httpx.Client(
            timeout=httpx.Timeout(30.0, connect=10.0),
            follow_redirects=True,
            http2=self.http2,
            headers=self.base_headers,
        )
        self._delay = self.min_delay_s
        self._consecutive_blocks = 0  # streak of 403/406s, drives the circuit breaker
        self._primed = False

    def _prime_session(self) -> None:
        """Optionally warm bot-management cookies via a homepage GET (once per instance).

        No-op unless ``prime_url`` is set. Best-effort: a failure here never aborts the run.
        """
        if self._primed:
            return
        self._primed = True  # attempt at most once, even on failure
        if not self.prime_url:
            return
        try:
            resp = self._client.get(self.prime_url, headers=self.prime_headers or _PRIME_HEADERS)
            logger.info(
                "[%s] session primed via %s → HTTP %d, %d cookies",
                self.source,
                self.prime_url,
                resp.status_code,
                len(self._client.cookies),
            )
        except Exception as exc:  # noqa: BLE001 — priming is best-effort
            logger.warning("[%s] session priming failed (continuing cold): %s", self.source, exc)

    def _pace(self) -> None:
        """Inter-request delay applied on every request — uniform(delay, 2×delay)."""
        time.sleep(random.uniform(self._delay, self._delay * 2))

    def _cooldown(self) -> None:
        """Escalating back-off after a 403/406 — doubles per consecutive block, capped + jitter."""
        secs = min(self._delay * (2**self._consecutive_blocks), self.cooldown_max_s)
        time.sleep(secs + random.uniform(0, self._delay))

    @retry(
        retry=retry_if_exception(_is_retryable),
        stop=stop_after_attempt(SCRAPER_MAX_RETRIES),
        wait=wait_exponential(multiplier=1, min=2, max=30) + wait_random(0, 2),
        reraise=True,
    )
    def _request(
        self,
        method: str,
        url: str,
        *,
        params: dict | None = None,
        json: object | None = None,
        headers: dict | None = None,
    ) -> httpx.Response | None:
        """Make one paced, retrying, block-aware request. Supports GET (params) and POST (json).

        Returns the ``httpx.Response`` on success (the caller parses ``.text``/``.json()``);
        returns ``None`` on a non-blocking skip (404) after pacing; raises
        :class:`ScraperBlockedError` after ``block_threshold`` consecutive 403/406; re-raises
        429/5xx so the tenacity ``@retry`` wrapping this method backs off and retries.
        """
        self._prime_session()
        response = self._client.request(method, url, params=params, json=json, headers=headers)
        try:
            response.raise_for_status()
        except httpx.HTTPStatusError as exc:
            status = exc.response.status_code
            logger.warning("[%s] HTTP %d on %s", self.source, status, url)
            if status in (403, 406):
                self._consecutive_blocks += 1
                self._cooldown()
                if self._consecutive_blocks >= self.block_threshold:
                    raise ScraperBlockedError(
                        f"{self._consecutive_blocks} consecutive {status}s from {self.source}"
                    ) from exc
                return None
            if status == 404:
                self._pace()
                return None
            raise  # 429/5xx — retried by tenacity
        self._consecutive_blocks = 0  # a success clears the block streak
        self._pace()
        return response

    def close(self) -> None:
        """Release the underlying HTTP connection pool."""
        self._client.close()

    def __enter__(self) -> HttpScraper:
        return self

    def __exit__(self, *args: object) -> None:
        self.close()
